const fs = require('fs').promises;
const https = require('https');
const path = require('path');
const { execSync } = require('child_process');

const API_KEY = process.env.OPENROUTER_API_KEY;
const RUN_NUM = process.env.GITHUB_RUN_NUMBER || 'local';

// ── AI API ──
function aiAsk(prompt, maxTokens) {
  return new Promise((resolve) => {
    if (!API_KEY) { resolve(''); return; }
    const data = JSON.stringify({
      model: 'anthropic/claude-3.5-sonnet',
      messages: [
        { role: 'system', content: 'You are Bude Tech CEO. Be concise.' },
        { role: 'user', content: prompt }
      ],
      max_tokens: maxTokens || 800,
      temperature: 0.5
    });
    const req = https.request({
      hostname: 'openrouter.ai',
      path: '/api/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + API_KEY,
        'HTTP-Referer': 'https://github.com/bude404-ops/bude-tech',
        'X-Title': 'Bude Tech CEO'
      },
      timeout: 15000
    }, (res) => {
      let body = '';
      res.on('data', c => body += c);
      res.on('end', () => {
        try { resolve(JSON.parse(body).choices[0].message.content); }
        catch { resolve(''); }
      });
    });
    req.on('error', () => resolve(''));
    req.on('timeout', () => { req.destroy(); resolve(''); });
    req.write(data);
    req.end();
  });
}

// ── Write file helper ──
async function writeFile(fp, content) {
  const dir = path.dirname(fp);
  if (dir !== '.') await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(fp, content);
}

// ── Module: memory.js ──
const memoryModule = [
  "const fs = require('fs').promises;",
  "",
  "class Memory {",
  "  constructor() {",
  "    this.file = 'ceo/memory.json';",
  "    this.data = {};",
  "  }",
  "  async load() {",
  "    try { this.data = JSON.parse(await fs.readFile(this.file, 'utf8')); }",
  "    catch { this.data = { runs: 0 }; }",
  "    this.data.runs = (this.data.runs || 0) + 1;",
  "  }",
  "  async save() {",
  "    await fs.mkdir('ceo', { recursive: true });",
  "    await fs.writeFile(this.file, JSON.stringify(this.data, null, 2));",
  "  }",
  "  get(k) { return this.data[k]; }",
  "  set(k, v) { this.data[k] = v; }",
  "}",
  "",
  "module.exports = Memory;"
].join('\n');

// ── Module: builder.js ──
const builderModule = [
  "const fs = require('fs').promises;",
  "const path = require('path');",
  "",
  "class Builder {",
  "  async buildFeature(specs) {",
  "    const name = specs.name || 'feature_' + Date.now();",
  "    const dir = 'projects/' + name;",
  "    await fs.mkdir(dir, { recursive: true });",
  "    await fs.writeFile(dir + '/index.js', '// ' + specs.description + '\\nmodule.exports = {};');",
  "    await fs.writeFile(dir + '/package.json', JSON.stringify({ name: name, version: '1.0.0', main: 'index.js' }, null, 2));",
  "    return { summary: 'Built ' + name };",
  "  }",
  "  async writeCode(fp, desc) {",
  "    await fs.mkdir(path.dirname(fp) || '.', { recursive: true });",
  "    await fs.writeFile(fp, '// ' + desc + '\\n');",
  "    return { summary: 'Wrote ' + fp };",
  "  }",
  "  async fixBug(bug) {",
  "    try {",
  "      const code = await fs.readFile(bug.file, 'utf8');",
  "      await fs.writeFile(bug.file + '.bak', code);",
  "      await fs.writeFile(bug.file, code + '\\n// Fixed');",
  "      return { summary: 'Fixed ' + bug.file };",
  "    } catch { return { summary: 'Failed' }; }",
  "  }",
  "}",
  "",
  "module.exports = Builder;"
].join('\n');

// ── Module: marketer.js ──
const marketerModule = [
  "const fs = require('fs').promises;",
  "",
  "class Marketer {",
  "  async updateDocs() {",
  "    const readme = '# Bude Tech\\n\\nAutonomous AI company.\\n\\n## Projects\\n\\nSee /projects/\\n\\n## License\\n\\nMIT';",
  "    await fs.writeFile('README.md', readme);",
  "    return { summary: 'Updated README' };",
  "  }",
  "  async createContent(type, topic) {",
  "    await fs.mkdir('content', { recursive: true });",
  "    const file = 'content/' + type + '_' + Date.now() + '.md';",
  "    await fs.writeFile(file, '# ' + topic + '\\n\\nGenerated by CEO.\\n');",
  "    return { summary: 'Created ' + file };",
  "  }",
  "}",
  "",
  "module.exports = Marketer;"
].join('\n');

// ── Module: learner.js ──
const learnerModule = [
  "const fs = require('fs').promises;",
  "",
  "class Learner {",
  "  constructor() {",
  "    this.kbFile = 'ceo/knowledge.json';",
  "    this.failFile = 'ceo/failures.json';",
  "    this.kb = {};",
  "    this.failures = [];",
  "  }",
  "  async load() {",
  "    try { this.kb = JSON.parse(await fs.readFile(this.kbFile, 'utf8')); }",
  "    catch { this.kb = { created: new Date().toISOString(), patterns: [] }; }",
  "    try { this.failures = JSON.parse(await fs.readFile(this.failFile, 'utf8')); }",
  "    catch { this.failures = []; }",
  "  }",
  "  async recordFailure(action, err) {",
  "    this.failures.push({ t: new Date().toISOString(), action: action.type, err: err.message });",
  "    if (this.failures.length > 50) this.failures = this.failures.slice(-50);",
  "    await this.saveFails();",
  "  }",
  "  async getRecent(n) { return this.failures.slice(-n); }",
  "  async saveFails() {",
  "    await fs.mkdir('ceo', { recursive: true });",
  "    await fs.writeFile(this.failFile, JSON.stringify(this.failures, null, 2));",
  "  }",
  "}",
  "",
  "module.exports = Learner;"
].join('\n');

// ── Module: communicator.js ──
const communicatorModule = [
  "const https = require('https');",
  "",
  "class Communicator {",
  "  constructor() {",
  "    this.key = process.env.OPENROUTER_API_KEY;",
  "  }",
  "  async checkAPI() {",
  "    if (!this.key) return false;",
  "    return new Promise(r => {",
  "      const req = https.request({",
  "        hostname: 'openrouter.ai',",
  "        path: '/api/v1/auth/key',",
  "        method: 'GET',",
  "        headers: { 'Authorization': 'Bearer ' + this.key },",
  "        timeout: 5000",
  "      }, res => r(res.statusCode === 200));",
  "      req.on('error', () => r(false));",
  "      req.on('timeout', () => { req.destroy(); r(false); });",
  "      req.end();",
  "    });",
  "  }",
  "}",
  "",
  "module.exports = Communicator;"
].join('\n');

// ── Script: learn.js ──
const learnScript = [
  "const fs = require('fs').promises;",
  "",
  "async function main() {",
  "  console.log('Reflecting...');",
  "  let memory;",
  "  try { memory = JSON.parse(await fs.readFile('ceo/memory.json', 'utf8')); }",
  "  catch { console.log('No memory'); return; }",
  "  console.log('Runs:', memory.runs || 0);",
  "  console.log('Done.');",
  "}",
  "",
  "main().catch(console.error);"
].join('\n');

// ── Script: persist.js ──
const persistScript = [
  "const fs = require('fs').promises;",
  "",
  "async function main() {",
  "  console.log('Saving...');",
  "  const dirs = ['ceo/reports', 'ceo/strategies', 'projects', 'content'];",
  "  for (const dir of dirs) {",
  "    await fs.mkdir(dir, { recursive: true });",
  "    await fs.writeFile(dir + '/.gitkeep', '');",
  "  }",
  "  console.log('Done.');",
  "}",
  "",
  "main().catch(console.error);"
].join('\n');

// ── package.json ──
const packageJson = JSON.stringify({
  name: 'bude-tech',
  version: '2.0.0',
  description: 'Autonomous AI Company',
  main: 'ceo/brain.js',
  scripts: { start: 'node ceo/brain.js', test: 'node --test' },
  keywords: ['ai', 'autonomous'],
  author: 'Bude CEO',
  license: 'MIT',
  engines: { node: '>=18.0.0' }
}, null, 2);

// ── .gitignore ──
const gitignore = [
  'node_modules/',
  'package-lock.json',
  '.env',
  '*.log',
  '*.backup',
  '*.bak',
  '.DS_Store'
].join('\n');

// ── All files to bootstrap ──
const MODULES = {
  'ceo/modules/memory.js': memoryModule,
  'ceo/modules/builder.js': builderModule,
  'ceo/modules/marketer.js': marketerModule,
  'ceo/modules/learner.js': learnerModule,
  'ceo/modules/communicator.js': communicatorModule,
  'ceo/learn.js': learnScript,
  'ceo/persist.js': persistScript,
  'package.json': packageJson,
  '.gitignore': gitignore
};

// ═══════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════
async function main() {
  console.log('[CEO] BUDE TECH v4.0 | Run:', RUN_NUM);
  
  // Load memory
  let memory;
  try {
    memory = JSON.parse(await fs.readFile('ceo/memory.json', 'utf8'));
  } catch {
    memory = { runs: 0, files: 0 };
  }
  memory.runs = (memory.runs || 0) + 1;
  
  // Bootstrap: create missing files
  let created = 0;
  for (const [fp, content] of Object.entries(MODULES)) {
    try {
      await fs.access(fp);
      console.log('[OK]', fp);
    } catch {
      await writeFile(fp, content);
      created++;
      console.log('[CREATE]', fp);
    }
  }
  
  // Create dirs
  for (const dir of ['projects', 'content', 'ceo/reports', 'ceo/strategies']) {
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(dir + '/.gitkeep', '');
  }
  
  console.log('Created', created, 'files');
  memory.files = (memory.files || 0) + created;
  
  // Count total files
  let fileCount = 0;
  try {
    fileCount = parseInt(execSync('find . -type f -not -path "./.git/*" -not -path "./node_modules/*" | wc -l', { encoding: 'utf8' }).trim());
  } catch {}
  console.log('Total files:', fileCount);
  
  // Execute actions
  let done = 0;
  
  // Action 1: Build a feature
  console.log('[ACTION] Build feature');
  try {
    const name = 'feature_' + Date.now();
    const dir = 'projects/' + name;
    await fs.mkdir(dir, { recursive: true });
    const code = await aiAsk('Write a 10-line Node.js utility function. Output ONLY code.', 600);
    const clean = code.replace(/```[\w]*\n?/g, '').replace(/```/g, '').trim();
    await fs.writeFile(dir + '/index.js', clean || '// Feature\nmodule.exports = {};');
    await fs.writeFile(dir + '/package.json', JSON.stringify({ name: name, version: '1.0.0', main: 'index.js' }, null, 2));
    console.log('[OK] Built', name);
    done++;
  } catch (err) {
    console.log('[FAIL]', err.message);
  }
  
  // Action 2: Update README
  console.log('[ACTION] Update README');
  try {
    const readme = await aiAsk('Write a short README.md for Bude Tech, an autonomous AI company. Output markdown.', 800);
    await fs.writeFile('README.md', readme || '# Bude Tech\n\nAutonomous AI company.\n');
    console.log('[OK] Updated README');
    done++;
  } catch (err) {
    console.log('[FAIL]', err.message);
  }
  
  // Action 3: Security audit
  console.log('[ACTION] Security audit');
  try {
    const issues = [];
    const jsFiles = execSync('find . -name "*.js" -not -path "./node_modules/*" -not -path "./.git/*"', { encoding: 'utf8' }).trim().split('\n').filter(Boolean);
    for (const f of jsFiles) {
      const c = await fs.readFile(f, 'utf8');
      if (/password\s*=\s*["'][^"']+["']/i.test(c)) issues.push({ file: f, issue: 'Hardcoded password' });
      if (/eval\s*\(/.test(c)) issues.push({ file: f, issue: 'eval()' });
    }
    await fs.mkdir('ceo/reports', { recursive: true });
    await fs.writeFile('ceo/reports/security.json', JSON.stringify({ scanned: jsFiles.length, issues, time: new Date().toISOString() }, null, 2));
    console.log('[OK] Audit:', issues.length, 'issues');
    done++;
  } catch (err) {
    console.log('[FAIL]', err.message);
  }
  
  // Save memory
  memory.lastResult = { done, fileCount };
  await fs.mkdir('ceo', { recursive: true });
  await fs.writeFile('ceo/memory.json', JSON.stringify(memory, null, 2));
  await fs.writeFile('ceo/last_action.txt', 'CEO run | ' + done + ' done');
  
  // Report
  const report = '# CEO Run ' + RUN_NUM + '\n\nDone: ' + done + '\nFiles: ' + fileCount + '\n\n*Autonomous CEO*';
  await fs.writeFile('ceo/reports/run_' + RUN_NUM + '.md', report);
  
  console.log('\n[CEO] Done. ' + done + ' actions completed.');
  
  // FORCE EXIT — cannot hang
  process.exit(0);
}

// Safety: hard kill after 7 minutes
setTimeout(() => {
  console.log('[CEO] Timeout');
  process.exit(0);
}, 7 * 60 * 1000);

// Run
main().catch(err => {
  console.error('[CEO] Fatal:', err.message);
  process.exit(1);
});
