#!/usr/bin/env node
/**
 * BUDE TECH CEO v4.1 — ORDER-AWARE
 * 
 * Every run:
 * 1. Bootstrap (create missing files)
 * 2. Check ceo/orders.txt for commands
 * 3. Execute orders
 * 4. Do normal autonomous work
 * 5. Report results
 */

const fs = require('fs').promises;
const https = require('https');
const path = require('path');
const { execSync } = require('child_process');

const API_KEY = process.env.OPENROUTER_API_KEY;
const RUN_NUM = process.env.GITHUB_RUN_NUMBER || 'local';

// ── AI API ──
function aiAsk(prompt, maxTokens) {
  return new Promise((resolve) => {
    if (!API_KEY) { resolve(''); return; }
    const data = JSON.stringify({
      model: 'anthropic/claude-3.5-sonnet',
      messages: [
        { role: 'system', content: 'You are Bude Tech CEO. Be concise. Output code only when asked.' },
        { role: 'user', content: prompt }
      ],
      max_tokens: maxTokens || 1500,
      temperature: 0.5
    });
    const req = https.request({
      hostname: 'openrouter.ai',
      path: '/api/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + API_KEY,
        'HTTP-Referer': 'https://github.com/bude404-ops/bude-tech',
        'X-Title': 'Bude Tech CEO'
      },
      timeout: 20000
    }, (res) => {
      let body = '';
      res.on('data', c => body += c);
      res.on('end', () => {
        try { resolve(JSON.parse(body).choices[0].message.content); }
        catch { resolve(''); }
      });
    });
    req.on('error', () => resolve(''));
    req.on('timeout', () => { req.destroy(); resolve(''); });
    req.write(data);
    req.end();
  });
}

// ── Write file helper ──
async function writeFile(fp, content) {
  const dir = path.dirname(fp);
  if (dir !== '.') await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(fp, content);
}

// ── Module templates ──
const MODULES = {
  'ceo/modules/memory.js': [
    "const fs = require('fs').promises;",
    "class Memory {",
    "  constructor() { this.file = 'ceo/memory.json'; this.data = {}; }",
    "  async load() { try { this.data = JSON.parse(await fs.readFile(this.file, 'utf8')); } catch { this.data = { runs: 0 }; } this.data.runs = (this.data.runs || 0) + 1; }",
    "  async save() { await fs.mkdir('ceo', { recursive: true }); await fs.writeFile(this.file, JSON.stringify(this.data, null, 2)); }",
    "  get(k) { return this.data[k]; }",
    "  set(k, v) { this.data[k] = v; }",
    "}",
    "module.exports = Memory;"
  ].join('\n'),

  'ceo/modules/builder.js': [
    "const fs = require('fs').promises;",
    "const path = require('path');",
    "class Builder {",
    "  async buildFeature(specs) { const name = specs.name || 'feature_' + Date.now(); const dir = 'projects/' + name; await fs.mkdir(dir, { recursive: true }); await fs.writeFile(dir + '/index.js', '// ' + specs.description + '\nmodule.exports = {};'); await fs.writeFile(dir + '/package.json', JSON.stringify({ name: name, version: '1.0.0', main: 'index.js' }, null, 2)); return { summary: 'Built ' + name }; }",
    "  async writeCode(fp, desc) { await fs.mkdir(path.dirname(fp) || '.', { recursive: true }); await fs.writeFile(fp, '// ' + desc + '\n'); return { summary: 'Wrote ' + fp }; }",
    "  async fixBug(bug) { try { const code = await fs.readFile(bug.file, 'utf8'); await fs.writeFile(bug.file + '.bak', code); await fs.writeFile(bug.file, code + '\n// Fixed'); return { summary: 'Fixed ' + bug.file }; } catch { return { summary: 'Failed' }; } }",
    "}",
    "module.exports = Builder;"
  ].join('\n'),

  'ceo/modules/marketer.js': [
    "const fs = require('fs').promises;",
    "class Marketer {",
    "  async updateDocs() { const readme = '# Bude Tech\n\nAutonomous AI company.\n\n## Projects\n\nSee /projects/\n\n## License\n\nMIT'; await fs.writeFile('README.md', readme); return { summary: 'Updated README' }; }",
    "  async createContent(type, topic) { await fs.mkdir('content', { recursive: true }); const file = 'content/' + type + '_' + Date.now() + '.md'; await fs.writeFile(file, '# ' + topic + '\n\nGenerated by CEO.\n'); return { summary: 'Created ' + file }; }",
    "}",
    "module.exports = Marketer;"
  ].join('\n'),

  'ceo/modules/learner.js': [
    "const fs = require('fs').promises;",
    "class Learner {",
    "  constructor() { this.kbFile = 'ceo/knowledge.json'; this.failFile = 'ceo/failures.json'; this.kb = {}; this.failures = []; }",
    "  async load() { try { this.kb = JSON.parse(await fs.readFile(this.kbFile, 'utf8')); } catch { this.kb = { created: new Date().toISOString(), patterns: [] }; } try { this.failures = JSON.parse(await fs.readFile(this.failFile, 'utf8')); } catch { this.failures = []; } }",
    "  async recordFailure(action, err) { this.failures.push({ t: new Date().toISOString(), action: action.type, err: err.message }); if (this.failures.length > 50) this.failures = this.failures.slice(-50); await this.saveFails(); }",
    "  async saveFails() { await fs.mkdir('ceo', { recursive: true }); await fs.writeFile(this.failFile, JSON.stringify(this.failures, null, 2)); }",
    "}",
    "module.exports = Learner;"
  ].join('\n'),

  'ceo/modules/communicator.js': [
    "const https = require('https');",
    "class Communicator {",
    "  constructor() { this.key = process.env.OPENROUTER_API_KEY; }",
    "  async checkAPI() { if (!this.key) return false; return new Promise(r => { const req = https.request({ hostname: 'openrouter.ai', path: '/api/v1/auth/key', method: 'GET', headers: { 'Authorization': 'Bearer ' + this.key }, timeout: 5000 }, res => r(res.statusCode === 200)); req.on('error', () => r(false)); req.on('timeout', () => { req.destroy(); r(false); }); req.end(); }); }",
    "}",
    "module.exports = Communicator;"
  ].join('\n'),

  'ceo/learn.js': [
    "const fs = require('fs').promises;",
    "async function main() { console.log('Reflecting...'); let memory; try { memory = JSON.parse(await fs.readFile('ceo/memory.json', 'utf8')); } catch { console.log('No memory'); return; } console.log('Runs:', memory.runs || 0); console.log('Done.'); }",
    "main().catch(console.error);"
  ].join('\n'),

  'ceo/persist.js': [
    "const fs = require('fs').promises;",
    "async function main() { console.log('Saving...'); const dirs = ['ceo/reports', 'ceo/strategies', 'projects', 'content']; for (const dir of dirs) { await fs.mkdir(dir, { recursive: true }); await fs.writeFile(dir + '/.gitkeep', ''); } console.log('Done.'); }",
    "main().catch(console.error);"
  ].join('\n'),

  'package.json': JSON.stringify({
    name: 'bude-tech',
    version: '2.0.0',
    description: 'Autonomous AI Company',
    main: 'ceo/brain.js',
    scripts: { start: 'node ceo/brain.js', test: 'node --test' },
    keywords: ['ai', 'autonomous'],
    author: 'Bude CEO',
    license: 'MIT',
    engines: { node: '>=18.0.0' }
  }, null, 2),

  '.gitignore': 'node_modules/\npackage-lock.json\n.env\n*.log\n*.backup\n*.bak\n.DS_Store'
};

// ── DASHBOARD HTML ──
const DASHBOARD_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>Bude Tech CEO Dashboard</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #0a0a0f; color: #e0e0e0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.5; min-height: 100vh; padding-bottom: 80px; }
  .header { background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); padding: 20px 16px; border-bottom: 1px solid #2a2a4a; position: sticky; top: 0; z-index: 100; }
  .header h1 { font-size: 1.3rem; color: #00d4ff; display: flex; align-items: center; gap: 8px; }
  .header .subtitle { font-size: 0.75rem; color: #888; margin-top: 4px; }
  .status-bar { display: flex; gap: 8px; padding: 12px 16px; overflow-x: auto; background: #0f0f1a; border-bottom: 1px solid #1a1a2e; }
  .status-pill { background: #1a1a2e; border: 1px solid #2a2a4a; border-radius: 20px; padding: 6px 14px; font-size: 0.75rem; white-space: nowrap; display: flex; align-items: center; gap: 6px; }
  .status-pill .dot { width: 8px; height: 8px; border-radius: 50%; background: #00d4ff; animation: pulse 2s infinite; }
  @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.3; } }
  .card { background: #12121f; border: 1px solid #1e1e32; border-radius: 12px; margin: 12px 16px; padding: 16px; }
  .card h2 { font-size: 0.85rem; color: #888; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 12px; display: flex; align-items: center; gap: 8px; }
  .metric-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #1a1a2e; }
  .metric-row:last-child { border-bottom: none; }
  .metric-label { color: #888; font-size: 0.85rem; }
  .metric-value { color: #fff; font-weight: 600; font-size: 0.9rem; }
  .metric-value.green { color: #00ff88; }
  .metric-value.yellow { color: #ffcc00; }
  .progress-bar { height: 6px; background: #1a1a2e; border-radius: 3px; overflow: hidden; margin-top: 8px; }
  .progress-fill { height: 100%; background: linear-gradient(90deg, #00d4ff, #00ff88); border-radius: 3px; transition: width 0.5s ease; }
  .task-item { display: flex; align-items: center; gap: 10px; padding: 12px; background: #0f0f1a; border-radius: 8px; margin-bottom: 8px; border-left: 3px solid #00d4ff; }
  .task-item.done { border-left-color: #00ff88; }
  .task-item.fail { border-left-color: #ff4444; }
  .task-icon { font-size: 1.2rem; }
  .task-text { flex: 1; font-size: 0.85rem; }
  .task-time { font-size: 0.7rem; color: #666; }
  .refresh-btn { position: fixed; bottom: 20px; right: 20px; width: 56px; height: 56px; border-radius: 50%; background: linear-gradient(135deg, #00d4ff, #0099cc); border: none; color: #fff; font-size: 1.5rem; display: flex; align-items: center; justify-content: center; box-shadow: 0 4px 20px rgba(0, 212, 255, 0.3); cursor: pointer; z-index: 200; }
  .refresh-btn.spin { animation: spin 1s linear infinite; }
  @keyframes spin { to { transform: rotate(360deg); } }
  .empty-state { text-align: center; padding: 40px 20px; color: #555; font-size: 0.85rem; }
  .log-entry { font-family: 'SF Mono', Monaco, monospace; font-size: 0.75rem; padding: 6px 0; border-bottom: 1px solid #1a1a2e; color: #aaa; }
  .log-entry:last-child { border-bottom: none; }
  .timestamp { color: #00d4ff; }
  .error-msg { color: #ff4444; }
  .success-msg { color: #00ff88; }
</style>
</head>
<body>
<div class="header">
  <h1>🤖 Bude Tech CEO</h1>
  <div class="subtitle">Autonomous AI Company Dashboard</div>
</div>
<div class="status-bar">
  <div class="status-pill"><span class="dot"></span><span id="status-text">Loading...</span></div>
  <div class="status-pill">📊 <span id="run-count">--</span> runs</div>
  <div class="status-pill">📁 <span id="file-count">--</span> files</div>
</div>
<div class="card">
  <h2>📊 Company Health</h2>
  <div class="metric-row"><span class="metric-label">Code Quality</span><span class="metric-value" id="quality">--</span></div>
  <div class="progress-bar"><div class="progress-fill" id="quality-bar" style="width: 0%"></div></div>
  <div class="metric-row" style="margin-top: 12px;"><span class="metric-label">Features Built</span><span class="metric-value green" id="features">--</span></div>
  <div class="metric-row"><span class="metric-label">Files Created</span><span class="metric-value" id="files-created">--</span></div>
  <div class="metric-row"><span class="metric-label">Last Run</span><span class="metric-value" id="last-run">--</span></div>
  <div class="metric-row"><span class="metric-label">Established</span><span class="metric-value" id="established">--</span></div>
</div>
<div class="card">
  <h2>⚡ Recent Activity</h2>
  <div id="activity-list"><div class="empty-state">Loading activity...</div></div>
</div>
<div class="card">
  <h2>📋 Latest Run Report</h2>
  <div id="report-content"><div class="empty-state">No reports yet</div></div>
</div>
<div class="card">
  <h2>📝 System Log</h2>
  <div id="log-content"><div class="empty-state">Waiting for logs...</div></div>
</div>
<button class="refresh-btn" id="refresh" onclick="loadData()">🔄</button>
<script>
const REPO = 'bude404-ops/bude-tech';
const BRANCH = 'main';
const BASE = 'https://raw.githubusercontent.com/' + REPO + '/' + BRANCH + '/';
async function fetchJSON(path) { try { const res = await fetch(BASE + path + '?t=' + Date.now()); if (!res.ok) return null; return await res.json(); } catch { return null; } }
async function fetchText(path) { try { const res = await fetch(BASE + path + '?t=' + Date.now()); if (!res.ok) return null; return await res.text(); } catch { return null; } }
async function loadData() {
  const btn = document.getElementById('refresh'); btn.classList.add('spin');
  const memory = await fetchJSON('ceo/memory.json');
  if (memory) {
    document.getElementById('run-count').textContent = memory.runs || 0;
    document.getElementById('file-count').textContent = memory.files || 0;
    document.getElementById('files-created').textContent = memory.files_created || 0;
    document.getElementById('features').textContent = memory.files_created || 0;
    document.getElementById('last-run').textContent = memory.lastRun ? new Date(memory.lastRun).toLocaleString() : 'Never';
    document.getElementById('established').textContent = memory.established ? '✅ YES' : '⏳ Building...';
    document.getElementById('established').className = 'metric-value ' + (memory.established ? 'green' : 'yellow');
    const health = memory.health || {}; const quality = health.quality || 0;
    document.getElementById('quality').textContent = quality + '/100';
    document.getElementById('quality-bar').style.width = quality + '%';
    document.getElementById('status-text').textContent = memory.established ? 'Active' : 'Bootstrapping';
  }
  const report = await fetchText('ceo/reports/run_' + (memory ? memory.runs : 1) + '.md');
  if (report) { document.getElementById('report-content').innerHTML = '<pre style="white-space:pre-wrap;font-size:0.8rem;color:#ccc;">' + report.replace(/</g, '&lt;') + '</pre>'; }
  const activityList = document.getElementById('activity-list');
  if (memory && memory.plan && memory.plan.actions) {
    const actions = memory.plan.actions;
    if (actions.length > 0) {
      activityList.innerHTML = actions.map(a => {
        const icon = a.status === 'completed' ? '✅' : a.status === 'failed' ? '❌' : '⏳';
        const cls = a.status === 'completed' ? 'done' : a.status === 'failed' ? 'fail' : '';
        return '<div class="task-item ' + cls + '"><span class="task-icon">' + icon + '</span><div style="flex:1"><div class="task-text">' + a.type + ': ' + a.description + '</div><div class="task-time">' + (a.status || 'pending') + '</div></div></div>';
      }).join('');
    } else { activityList.innerHTML = '<div class="empty-state">No actions this run</div>'; }
  }
  const logDiv = document.getElementById('log-content'); let logHTML = '';
  if (memory && memory.failures && memory.failures.length > 0) {
    logHTML += memory.failures.slice(-5).reverse().map(f => '<div class="log-entry"><span class="timestamp">' + new Date(f.t).toLocaleTimeString() + '</span> <span class="error-msg">❌ ' + f.action + ': ' + f.err + '</span></div>').join('');
  }
  if (memory && memory.lastResult) {
    logHTML += '<div class="log-entry"><span class="timestamp">' + new Date().toLocaleTimeString() + '</span> <span class="success-msg">✅ Last run: ' + memory.lastResult.done + ' done, ' + (memory.lastResult.fail || 0) + ' failed</span></div>';
  }
  if (!logHTML) { logHTML = '<div class="empty-state">No logs yet. First run in progress...</div>'; }
  logDiv.innerHTML = logHTML;
  btn.classList.remove('spin');
}
loadData();
setInterval(loadData, 30000);
</script>
</body>
</html>`;

// ── PAGES WORKFLOW ──
const PAGES_WORKFLOW = `name: Deploy Dashboard

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dashboard'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;

// ═══════════════════════════════════════════════════════
// CHECK ORDERS
// ═══════════════════════════════════════════════════════
async function checkOrders(memory) {
  console.log('[ORDERS] Checking for commands...');
  
  let orders = '';
  try {
    orders = await fs.readFile('ceo/orders.txt', 'utf8');
  } catch {
    console.log('[ORDERS] No orders file found');
    return { executed: [], hasOrders: false };
  }
  
  if (!orders.trim() || orders.trim().startsWith('# Orders executed')) {
    console.log('[ORDERS] No new orders');
    return { executed: [], hasOrders: false };
  }
  
  console.log('[ORDERS] Found orders, executing...');
  const results = [];
  
  // Check for dashboard order
  if (orders.toLowerCase().includes('dashboard') || orders.toLowerCase().includes('deploy')) {
    console.log('[ORDERS] → Building dashboard');
    try {
      await fs.mkdir('dashboard', { recursive: true });
      await fs.writeFile('dashboard/index.html', DASHBOARD_HTML);
      console.log('[ORDERS] ✅ dashboard/index.html created');
      results.push('Created dashboard/index.html');
      
      await fs.mkdir('.github/workflows', { recursive: true });
      await fs.writeFile('.github/workflows/pages.yml', PAGES_WORKFLOW);
      console.log('[ORDERS] ✅ .github/workflows/pages.yml created');
      results.push('Created Pages deploy workflow');
      
      let readme = '# Bude Tech\n\n🤖 Autonomous AI Company\n\n## Dashboard\n\n📱 [View CEO Dashboard](https://bude404-ops.github.io/bude-tech/)\n\n## Projects\n\nSee /projects/ for AI-built products.\n\n## License\n\nMIT';
      try {
        const existing = await fs.readFile('README.md', 'utf8');
        if (existing.indexOf('Dashboard') === -1) {
          readme = existing + '\n\n## Dashboard\n\n📱 [View CEO Dashboard](https://bude404-ops.github.io/bude-tech/)\n';
        } else { readme = existing; }
      } catch {}
      await fs.writeFile('README.md', readme);
      console.log('[ORDERS] ✅ README.md updated with dashboard link');
      results.push('Updated README with dashboard URL');
      
    } catch (err) {
      console.log('[ORDERS] ❌ Dashboard build failed:', err.message);
      results.push('Dashboard failed: ' + err.message);
    }
  }
  
  // Check for build feature order
  if (orders.toLowerCase().includes('build feature') || orders.toLowerCase().includes('build:')) {
    console.log('[ORDERS] → Building feature from orders');
    try {
      const match = orders.match(/build[:\\s]+(.+)/i);
      const desc = match ? match[1].trim() : 'AI feature';
      const name = 'feature_' + Date.now();
      const dir = 'projects/' + name;
      await fs.mkdir(dir, { recursive: true });
      const code = await aiAsk('Write a tiny Node.js module for: ' + desc + '. 15 lines. Output ONLY code.', 600);
      const clean = code.replace(/```[\w]*\n?/g, '').replace(/```/g, '').trim();
      await fs.writeFile(dir + '/index.js', clean || '// ' + desc + '\nmodule.exports = {};');
      await fs.writeFile(dir + '/package.json', JSON.stringify({ name: name, version: '1.0.0', main: 'index.js' }, null, 2));
      console.log('[ORDERS] ✅ Built feature:', name);
      results.push('Built feature: ' + name);
    } catch (err) {
      console.log('[ORDERS] ❌ Feature build failed:', err.message);
      results.push('Feature failed: ' + err.message);
    }
  }
  
  // Save history and clear orders
  const historyEntry = {
    timestamp: new Date().toISOString(),
    orders: orders.slice(0, 500),
    results: results
  };
  
  let history = [];
  try {
    history = JSON.parse(await fs.readFile('ceo/orders_history.json', 'utf8'));
  } catch {}
  history.push(historyEntry);
  if (history.length > 20) history = history.slice(-20);
  
  await fs.writeFile('ceo/orders_history.json', JSON.stringify(history, null, 2));
  await fs.writeFile('ceo/orders.txt', '# Orders executed on ' + new Date().toISOString() + '\n# Results: ' + results.join(', ') + '\n# Write new orders below:\n');
  
  console.log('[ORDERS] Cleared. Results:', results.join(', '));
  return { executed: results, hasOrders: true };
}

// ═══════════════════════════════════════════════════════
// BOOTSTRAP
// ═══════════════════════════════════════════════════════
async function bootstrap(memory) {
  console.log('[BOOTSTRAP] Checking files...');
  let created = 0;
  for (const [fp, content] of Object.entries(MODULES)) {
    try {
      await fs.access(fp);
    } catch {
      await writeFile(fp, content);
      created++;
      console.log('[BOOTSTRAP] Created', fp);
    }
  }
  for (const dir of ['projects', 'content', 'ceo/reports', 'ceo/strategies']) {
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(dir + '/.gitkeep', '');
  }
  memory.files_created = (memory.files_created || 0) + created;
  console.log('[BOOTSTRAP]', created, 'files created');
}

// ═══════════════════════════════════════════════════════
// ANALYZE
// ═══════════════════════════════════════════════════════
async function analyze() {
  try {
    const files = execSync('find . -type f -not -path "./.git/*" -not -path "./node_modules/*" | wc -l', { encoding: 'utf8' }).trim();
    let quality = 50;
    try { await fs.access('README.md'); quality += 15; } catch {}
    try { await fs.access('.github/workflows'); quality += 15; } catch {}
    try { await fs.access('projects'); quality += 10; } catch {}
    try { await fs.access('tests'); quality += 10; } catch {}
    return { files: parseInt(files), quality: Math.min(quality, 100) };
  } catch {
    return { files: 0, quality: 0 };
  }
}

// ═══════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════
async function main() {
  const start = Date.now();
  console.log('[CEO] BUDE TECH v4.1 | Run:', RUN_NUM);
  
  // Load memory
  let memory;
  try {
    memory = JSON.parse(await fs.readFile('ceo/memory.json', 'utf8'));
  } catch {
    memory = { runs: 0, files_created: 0, failures: [] };
  }
  memory.runs = (memory.runs || 0) + 1;
  memory.lastRun = new Date().toISOString();
  
  // Bootstrap
  await bootstrap(memory);
  
  // CHECK AND EXECUTE ORDERS FIRST
  const orderResult = await checkOrders(memory);
  
  // Normal autonomous work
  const health = await analyze();
  memory.health = health;
  console.log('[CEO] Files:', health.files, '| Quality:', health.quality);
  
  // Build feature
  let done = orderResult.executed.length;
  console.log('[ACTION] Build feature');
  try {
    const name = 'feature_' + Date.now();
    const dir = 'projects/' + name;
    await fs.mkdir(dir, { recursive: true });
    const code = await aiAsk('Write a 10-line Node.js utility. Output ONLY code.', 600);
    const clean = code.replace(/```[\w]*\n?/g, '').replace(/```/g, '').trim();
    await fs.writeFile(dir + '/index.js', clean || '// Feature\nmodule.exports = {};');
    await fs.writeFile(dir + '/package.json', JSON.stringify({ name: name, version: '1.0.0', main: 'index.js' }, null, 2));
    console.log('[OK] Built', name);
    done++;
  } catch (err) {
    console.log('[FAIL]', err.message);
    memory.failures.push({ t: new Date().toISOString(), action: 'build_feature', err: err.message });
  }
  
  // Update README
  console.log('[ACTION] Update README');
  try {
    const readme = await aiAsk('Write a short README.md for Bude Tech AI company. Output markdown.', 800);
    await fs.writeFile('README.md', readme || '# Bude Tech\n\nAutonomous AI company.\n');
    console.log('[OK] Updated README');
    done++;
  } catch (err) {
    console.log('[FAIL]', err.message);
    memory.failures.push({ t: new Date().toISOString(), action: 'update_docs', err: err.message });
  }
  
  // Security audit
  console.log('[ACTION] Security audit');
  try {
    const issues = [];
    const jsFiles = execSync('find . -name "*.js" -not -path "./node_modules/*" -not -path "./.git/*"', { encoding: 'utf8' }).trim().split('\n').filter(Boolean);
    for (const f of jsFiles) {
      const c = await fs.readFile(f, 'utf8');
      if (/password\s*=\s*["'][^"']+["']/i.test(c)) issues.push({ file: f, issue: 'Hardcoded password' });
      if (/eval\s*\(/.test(c)) issues.push({ file: f, issue: 'eval()' });
    }
    await fs.mkdir('ceo/reports', { recursive: true });
    await fs.writeFile('ceo/reports/security.json', JSON.stringify({ scanned: jsFiles.length, issues, time: new Date().toISOString() }, null, 2));
    console.log('[OK] Audit:', issues.length, 'issues');
    done++;
  } catch (err) {
    console.log('[FAIL]', err.message);
  }
  
  // Save
  memory.established = memory.runs > 5 && memory.files_created > 5;
  memory.lastResult = { done, fileCount: health.files };
  await fs.mkdir('ceo', { recursive: true });
  await fs.writeFile('ceo/memory.json', JSON.stringify(memory, null, 2));
  await fs.writeFile('ceo/last_action.txt', 'CEO run | ' + done + ' done');
  
  const report = '# CEO Run ' + RUN_NUM + '\n\nDone: ' + done + '\nFiles: ' + health.files + '\nOrders: ' + (orderResult.hasOrders ? orderResult.executed.join(', ') : 'none') + '\n\n*Autonomous CEO*';
  await fs.writeFile('ceo/reports/run_' + RUN_NUM + '.md', report);
  
  const duration = ((Date.now() - start) / 1000).toFixed(1);
  console.log('\n[CEO] Done in ' + duration + 's | ' + done + ' actions');
  if (memory.established) console.log('[CEO] 🚀 ESTABLISHED!');
  
  process.exit(0);
}

setTimeout(() => { console.log('[CEO] Timeout'); process.exit(0); }, 8 * 60 * 1000);
main().catch(err => { console.error('[CEO] Fatal:', err.message); process.exit(1); });
