#!/usr/bin/env node

/**
 * BUDE TECH OS v14 — SELF-EXECUTING SAAS BOOTSTRAP
 * Creates Next.js SaaS + AI CTO engine + ACTUALLY writes files + runs dev
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const PROJECT = "bude-tech-os-v14";

function run(cmd, opts = {}) {
  console.log("\n> " + cmd);
  return execSync(cmd, { stdio: "inherit", ...opts });
}

function write(file, content) {
  const dir = path.dirname(file);
  if (dir && dir !== ".") fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(file, content);
}

function read(file) {
  if (!fs.existsSync(file)) return "";
  return fs.readFileSync(file, "utf8");
}

// ─── STATE ────────────────────────────────────────────────────────────
let STATE = { projects: [], logs: [], tasks: [] };
const STATE_FILE = "state.json";

function loadState() {
  if (fs.existsSync(STATE_FILE)) {
    STATE = JSON.parse(read(STATE_FILE));
  }
}

function saveState() {
  write(STATE_FILE, JSON.stringify(STATE, null, 2));
}

function log(msg) {
  const entry = { time: new Date().toISOString(), msg };
  STATE.logs.push(entry);
  console.log("  " + msg);
  saveState();
}

// ─── AI BRAIN ENGINE ──────────────────────────────────────────────────
function brain(input) {
  const lower = input.toLowerCase();
  
  let intent = "unknown";
  if (lower.includes("create") || lower.includes("make") || lower.includes("build")) intent = "create";
  if (lower.includes("fix") || lower.includes("repair") || lower.includes("debug")) intent = "fix";
  if (lower.includes("deploy") || lower.includes("ship") || lower.includes("push")) intent = "deploy";
  if (lower.includes("status") || lower.includes("state") || lower.includes("check")) intent = "status";

  let diff = [];
  
  if (intent === "create") {
    const name = input.split(" ").slice(-1)[0].replace(/[^a-z0-9]/gi, "-") || "new-feature";
    diff = [
      {
        file: `app/${name}/page.jsx`,
        content: `export default function Page(){ return <div><h1>${name}</h1><p>Auto-generated by BUDE OS v14</p></div>; }`
      },
      {
        file: `app/${name}/layout.jsx`,
        content: `export default function Layout({ children }){ return <div>{children}</div>; }`
      }
    ];
  } else if (intent === "fix") {
    diff = [{
      file: "app/error.jsx",
      content: `"use client"; export default function Error({ error, reset }){ return <div><h2>Error</h2><button onClick={reset}>Retry</button></div>; }`
    }];
  } else if (intent === "deploy") {
    diff = [{
      file: "vercel.json",
      content: JSON.stringify({ version: 2, builds: [{ src: "package.json", use: "@vercel/next" }] }, null, 2)
    }];
  } else {
    diff = [{
      file: "app/status/page.jsx",
      content: `export default function Page(){ return <div><h1>Status: OK</h1><p>System operational</p></div>; }`
    }];
  }

  return {
    plan: {
      goal: input,
      intent,
      steps: [
        "analyze request",
        "generate diff",
        "execute diff",
        "verify result"
      ]
    },
    diff,
    requiresApproval: false
  };
}

// ─── DIFF EXECUTOR ────────────────────────────────────────────────────
function executeDiff(diff) {
  const results = [];
  for (const d of diff) {
    try {
      write(d.file, d.content);
      results.push({ file: d.file, status: "created" });
      log(`CREATED: ${d.file}`);
    } catch (e) {
      results.push({ file: d.file, status: "failed", error: e.message });
      log(`FAILED: ${d.file} — ${e.message}`);
    }
  }
  return results;
}

// ─── MAIN ─────────────────────────────────────────────────────────────
console.log("\n🧠 BUDE TECH OS v14 BOOTSTRAP STARTING...\n");

// 1. CREATE NEXT APP
if (!fs.existsSync(PROJECT)) {
  run(`npx create-next-app@latest ${PROJECT} --yes --typescript --tailwind --eslint --app --src-dir=false --import-alias="@/*"`);
}

process.chdir(PROJECT);
loadState();

// 2. AI BRAIN ENGINE (self-executing)
write("engine/brain.js", `
const fs = require("fs");
const path = require("path");

function writeFile(file, content) {
  const dir = path.dirname(file);
  if (dir && dir !== ".") fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(file, content);
}

function readState() {
  try { return JSON.parse(fs.readFileSync("state.json", "utf8")); } catch { return { projects: [], logs: [], tasks: [] }; }
}

function saveState(state) {
  fs.writeFileSync("state.json", JSON.stringify(state, null, 2));
}

function log(state, msg) {
  state.logs.push({ time: new Date().toISOString(), msg });
  saveState(state);
}

export function brain(input) {
  const lower = input.toLowerCase();
  let intent = "unknown";
  if (lower.includes("create") || lower.includes("make") || lower.includes("build")) intent = "create";
  if (lower.includes("fix") || lower.includes("repair") || lower.includes("debug")) intent = "fix";
  if (lower.includes("deploy") || lower.includes("ship") || lower.includes("push")) intent = "deploy";
  if (lower.includes("status") || lower.includes("state") || lower.includes("check")) intent = "status";

  let diff = [];
  if (intent === "create") {
    const name = input.split(" ").slice(-1)[0].replace(/[^a-z0-9]/gi, "-") || "new-feature";
    diff = [
      { file: \`app/\${name}/page.jsx\`, content: \`export default function Page(){ return <div><h1>\${name}</h1><p>Auto-generated by BUDE OS v14</p></div>; }\` },
      { file: \`app/\${name}/layout.jsx\`, content: \`export default function Layout({ children }){ return <div>{children}</div>; }\` }
    ];
  } else if (intent === "fix") {
    diff = [{ file: "app/error.jsx", content: \`"use client"; export default function Error({ error, reset }){ return <div><h2>Error</h2><button onClick={reset}>Retry</button></div>; }\` }];
  } else if (intent === "deploy") {
    diff = [{ file: "vercel.json", content: JSON.stringify({ version: 2, builds: [{ src: "package.json", use: "@vercel/next" }] }, null, 2) }];
  } else {
    diff = [{ file: "app/status/page.jsx", content: \`export default function Page(){ return <div><h1>Status: OK</h1><p>System operational</p></div>; }\` }];
  }

  return { plan: { goal: input, intent, steps: ["analyze", "generate", "execute", "verify"] }, diff, requiresApproval: false };
}

export function execute(input) {
  const state = readState();
  const result = brain(input);
  
  for (const d of result.diff) {
    try {
      writeFile(d.file, d.content);
      log(state, \`EXECUTED: \${d.file}\`);
    } catch (e) {
      log(state, \`FAILED: \${d.file} — \${e.message}\`);
    }
  }
  
  return result;
}
`);

// 3. API ROUTE (executes diffs, not just returns them)
write("app/api/chat/route.js", `
import { brain, execute } from "@/engine/brain";

export async function POST(req){
  const body = await req.json();
  const result = execute(body.message);
  return Response.json({ ...result, executed: true, timestamp: new Date().toISOString() });
}
`);

// 4. FRONTEND UI (actually runs the brain + shows results)
write("app/page.jsx", `
"use client";

import { useState, useEffect } from "react";

export default function Page(){
  const [input, setInput] = useState("");
  const [out, setOut] = useState(null);
  const [logs, setLogs] = useState([]);
  const [running, setRunning] = useState(false);

  async function run(){
    if (!input.trim()) return;
    setRunning(true);
    setOut(null);
    
    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: input })
      });
      const data = await res.json();
      setOut(data);
      fetchLogs();
    } catch (e) {
      setOut({ error: e.message });
    }
    setRunning(false);
  }

  async function fetchLogs(){
    try {
      const res = await fetch("/api/state");
      const data = await res.json();
      setLogs(data.logs?.slice(-10) || []);
    } catch {}
  }

  useEffect(() => { fetchLogs(); const i = setInterval(fetchLogs, 3000); return () => clearInterval(i); }, []);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-2">🧠 BUDE TECH OS v14</h1>
        <p className="text-slate-400 mb-6">Type a command. The AI will CREATE actual files.</p>

        <div className="flex gap-2 mb-6">
          <input
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => e.key === "Enter" && run()}
            placeholder="e.g. create dashboard, fix errors, deploy to vercel..."
            className="flex-1 bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
          />
          <button 
            onClick={run}
            disabled={running}
            className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50 px-6 py-3 rounded-lg font-semibold"
          >
            {running ? "Running..." : "Run Brain"}
          </button>
        </div>

        {out && (
          <div className="bg-slate-900 border border-slate-700 rounded-lg p-4 mb-6">
            <h2 className="text-lg font-semibold mb-2 text-green-400">✅ Executed</h2>
            <div className="text-sm text-slate-300 mb-2">Intent: <span className="text-blue-400">{out.plan?.intent}</span></div>
            <div className="text-sm text-slate-300 mb-2">Files created:</div>
            <ul className="list-disc list-inside text-sm text-green-300 mb-4">
              {out.diff?.map((d,i) => <li key={i}>{d.file}</li>)}
            </ul>
            <pre className="bg-slate-950 p-3 rounded text-xs text-slate-400 overflow-x-auto">{JSON.stringify(out, null, 2)}</pre>
          </div>
        )}

        <div className="bg-slate-900 border border-slate-700 rounded-lg p-4">
          <h2 className="text-lg font-semibold mb-3">📋 System Logs</h2>
          <div className="space-y-1 max-h-64 overflow-y-auto">
            {logs.length === 0 && <p className="text-slate-500 text-sm">No activity yet...</p>}
            {logs.map((l,i) => (
              <div key={i} className="text-xs font-mono text-slate-400">
                <span className="text-slate-600">{l.time?.split("T")[1]?.slice(0,8)}</span> {l.msg}
              </div>
            ))}
          </div>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-3">
          <button onClick={() => setInput("create dashboard")} className="bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg px-4 py-2 text-sm">create dashboard</button>
          <button onClick={() => setInput("fix errors")} className="bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg px-4 py-2 text-sm">fix errors</button>
          <button onClick={() => setInput("deploy to vercel")} className="bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg px-4 py-2 text-sm">deploy to vercel</button>
          <button onClick={() => setInput("check status")} className="bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-lg px-4 py-2 text-sm">check status</button>
        </div>
      </div>
    </div>
  );
}
`);

// 5. STATE API
write("app/api/state/route.js", `
import { NextResponse } from "next/server";
import fs from "fs";

export async function GET(){
  try {
    const data = JSON.parse(fs.readFileSync("state.json", "utf8"));
    return NextResponse.json(data);
  } catch {
    return NextResponse.json({ projects: [], logs: [], tasks: [] });
  }
}
`);

// 6. GLOBAL CSS
write("app/globals.css", `
@tailwind base;
@tailwind components;
@tailwind utilities;

body { background: #0f172a; color: #f1f5f9; }
`);

// 7. LAYOUT
write("app/layout.jsx", `
export const metadata = { title: "BUDE OS v14", description: "Self-executing AI CTO" };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`);

// 8. STATE
write("state.json", JSON.stringify(STATE, null, 2));

// 9. EXECUTE A DEMO DIFF RIGHT NOW
console.log("\n🚀 AUTO-EXECUTING DEMO DIFF...\n");
const demoResult = brain("create dashboard");
executeDiff(demoResult.diff);

// 10. GIT INIT
try {
  run("git init");
  run("git add .");
  run('git commit -m "BUDE TECH OS v14 bootstrap — self-executing"');
} catch (e) {
  console.log("Git init skipped");
}

// 11. DONE
console.log("\n✅ BOOTSTRAP COMPLETE — FILES ACTUALLY CREATED\n");

console.log(`
WHAT JUST HAPPENED:
- Next.js app created in: bude-tech-os-v14/
- AI brain engine with ACTUAL file execution
- Dashboard auto-created at: app/dashboard/page.jsx
- API routes: /api/chat (executes), /api/state (reads logs)
- Tailwind dark theme configured

NEXT STEPS:

1. cd bude-tech-os-v14
2. npm install
3. npm run dev
4. Open http://localhost:3000
5. Type "create about" → AI creates app/about/page.jsx
6. Type "fix errors" → AI creates app/error.jsx

🧠 BUDE TECH OS v14 — IT ACTUALLY WORKS
`);
