#!/usr/bin/env node

require("dotenv").config();

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { execSync } = require("child_process");

/**
 * =========================
 * STATE
 * =========================
 */

const STATE_FILE = "data/state.json";

let STATE = loadState();

function loadState() {
  try {
    return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
  } catch {
    return {
      phase: "init",
      cycle: 0,
      tasks: [],
      logs: [],
      lastRun: null
    };
  }
}

function saveState() {
  fs.mkdirSync("data", { recursive: true });
  fs.writeFileSync(STATE_FILE, JSON.stringify(STATE, null, 2));
}

/**
 * =========================
 * LOGGING
 * =========================
 */

function log(msg) {
  console.log(`[CEO v11] ${msg}`);
  STATE.logs.push({ t: Date.now(), msg });
}

/**
 * =========================
 * GIT LAYER (FIXED + SAFE)
 * =========================
 */

function git(cmd) {
  try {
    const out = execSync(cmd, { encoding: "utf-8" });
    console.log(`🟢 ${cmd}`);
    return out;
  } catch (e) {
    console.log(`🔴 ${cmd}`);
    console.log(e.message);
    return null;
  }
}

function ensureGit() {
  if (!fs.existsSync(".git")) {
    log("Initializing git repo...");
    git("git init");
    git("git branch -M main");
  }

  const remote = git("git remote get-url origin");
  if (!remote) {
    log("Adding git remote...");
    git("git remote add origin https://github.com/Bude404-ops/Bude-Tech.git");
  }

  git('git config user.name "BUDE CEO"');
  git('git config user.email "ceo@bude.local"');
}

function commitPush(message) {
  log("Committing changes...");

  git("git add .");

  const commit = git(`git commit -m "${message}"`);

  if (!commit || commit.includes("nothing to commit")) {
    log("No changes to commit");
    return;
  }

  git("git push origin main");
  log("Pushed to GitHub");
}

/**
 * =========================
 * ENGINE (FILE CREATION)
 * =========================
 */

class Engine {
  add(task) {
    STATE.tasks.push({
      id: crypto.randomUUID(),
      status: "pending",
      created: Date.now(),
      ...task
    });
  }

  run() {
    const pending = STATE.tasks.filter(t => t.status === "pending");

    for (const t of pending) {
      try {
        log(`Executing: ${t.type}`);

        if (t.type === "file") {
          fs.mkdirSync(path.dirname(t.path), { recursive: true });
          fs.writeFileSync(t.path, t.content);
          log(`Wrote file: ${t.path}`);
        }

        if (t.type === "code") {
          fs.mkdirSync(path.dirname(t.path), { recursive: true });
          fs.writeFileSync(
            t.path,
            `// AUTO GENERATED FILE\nconsole.log("ACTIVE:", "${t.path}");`
          );
          log(`Generated code: ${t.path}`);
        }

        t.status = "done";
      } catch (e) {
        t.status = "failed";
        log(`ERROR: ${e.message}`);
      }
    }
  }
}

const ENGINE = new Engine();

/**
 * =========================
 * BOOTSTRAP
 * =========================
 */

function bootstrap() {
  log("Bootstrapping system...");

  ["core", "backend", "frontend", "data"].forEach(d =>
    fs.mkdirSync(d, { recursive: true })
  );

  ENGINE.add({
    type: "file",
    path: "frontend/index.html",
    content: "<h1>BUDE AUTONOMOUS SYSTEM ONLINE</h1>"
  });

  STATE.phase = "plan";
}

/**
 * =========================
 * PHASE SYSTEM
 * =========================
 */

function plan() {
  log("Planning phase");

  ENGINE.add({ type: "code", path: "backend/server.js" });
  ENGINE.add({ type: "code", path: "backend/api.js" });
  ENGINE.add({
    type: "file",
    path: "README.md",
    content: "# Autonomous System\nGenerated by BUDE CEO v11"
  });

  STATE.phase = "build";
  commitPush(`Phase PLAN cycle ${STATE.cycle}`);
}

function build() {
  log("Build phase");

  ENGINE.add({ type: "code", path: "frontend/app.js" });
  ENGINE.add({ type: "code", path: "frontend/sw.js" });

  STATE.phase = "finalize";
  commitPush(`Phase BUILD cycle ${STATE.cycle}`);
}

function finalize() {
  log("Finalizing system");

  ENGINE.add({
    type: "file",
    path: "package.json",
    content: JSON.stringify({
      name: "bude-autonomous-system",
      version: "1.0.0",
      scripts: { start: "node backend/server.js" }
    }, null, 2)
  });

  STATE.phase = "done";
  commitPush(`FINALIZED cycle ${STATE.cycle}`);
}

/**
 * =========================
 * MAIN LOOP
 * =========================
 */

function loop() {
  STATE.cycle++;
  STATE.lastRun = new Date().toISOString();

  console.log("\n==========================");
  log(`CYCLE ${STATE.cycle} | PHASE: ${STATE.phase}`);
  console.log("==========================\n");

  ensureGit();

  ENGINE.run();

  switch (STATE.phase) {
    case "init":
      bootstrap();
      break;

    case "plan":
      plan();
      break;

    case "build":
      build();
      break;

    case "finalize":
      finalize();
      break;

    case "done":
      log("SYSTEM COMPLETE");
      saveState();
      return;
  }

  saveState();

  setTimeout(loop, 5000);
}

/**
 * =========================
 * START
 * =========================
 */

log("Starting BUDE CEO v11");
loop();
