#!/usr/bin/env node

/**
 * BUDE TECH CEO v23 — AUTONOMOUS PR ENGINE
 * Issue → Classify → Patch → Branch → Commit → PR
 */

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { Octokit } = require("@octokit/rest");

/* =========================
   CONFIG
========================= */

const CONFIG = {
  owner: "bude404-ops",
  repo: "Bude-Tech",
  branchPrefix: "auto-v23"
};

/* =========================
   GITHUB CLIENT
========================= */

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

/* =========================
   FETCH ISSUES
========================= */

async function fetchIssues() {
  const res = await octokit.rest.issues.listForRepo({
    owner: CONFIG.owner,
    repo: CONFIG.repo,
    state: "open"
  });

  return res.data.filter(i => !i.pull_request);
}

/* =========================
   CLASSIFY ISSUE
========================= */

function classify(issue) {
  const text = (issue.title + " " + (issue.body || "")).toLowerCase();

  if (text.includes("bug")) return "bugfix";
  if (text.includes("ui")) return "frontend";
  if (text.includes("api")) return "backend";
  if (text.includes("refactor")) return "refactor";
  if (text.includes("feature")) return "feature";

  return "general";
}

/* =========================
   PATCH ENGINE (SAFE DEFAULTS)
========================= */

function generatePatch(issue, type) {
  if (type === "frontend") {
    return {
      file: "frontend/autofix.html",
      content: `
<!-- AUTO GENERATED UI PATCH -->
<h1>UI Update Applied</h1>
<p>Issue: ${issue.title}</p>
`
    };
  }

  if (type === "backend") {
    return {
      file: "backend/autofix.js",
      content: `
// AUTO GENERATED BACKEND PATCH
console.log("Patched issue: ${issue.title}");
`
    };
  }

  if (type === "bugfix") {
    return {
      file: "fixes/bugfix.log",
      content: `Bug handled: ${issue.title}\n`
    };
  }

  return {
    file: "general/task.log",
    content: `General task processed: ${issue.title}\n`
  };
}

/* =========================
   GIT HELPERS
========================= */

function run(cmd) {
  execSync(cmd, { stdio: "inherit" });
}

/* =========================
   EXECUTE ONE ISSUE
========================= */

async function handleIssue(issue) {
  const type = classify(issue);

  const patch = generatePatch(issue, type);

  const branch = `${CONFIG.branchPrefix}-${issue.number}`;

  console.log(`\n[V23] Processing Issue #${issue.number}: ${issue.title}`);
  console.log(`[V23] Type: ${type}`);
  console.log(`[V23] Branch: ${branch}`);

  // create branch
  run(`git checkout -b ${branch}`);

  // write file
  fs.mkdirSync(path.dirname(patch.file), { recursive: true });
  fs.writeFileSync(patch.file, patch.content);

  // commit
  run(`git add .`);
  run(`git commit -m "auto-fix: ${issue.title}"`);

  // push branch
  run(`git push origin ${branch}`);

  // create PR
  await octokit.rest.pulls.create({
    owner: CONFIG.owner,
    repo: CONFIG.repo,
    title: `AutoFix: ${issue.title}`,
    head: branch,
    base: "main",
    body: `Automated PR generated by BUDE CEO v23`
  });

  console.log(`[V23] PR created for issue #${issue.number}`);
}

/* =========================
   MAIN RUNNER
========================= */

async function run() {
  console.log("\n=========================");
  console.log(" BUDE TECH CEO v23 START ");
  console.log("=========================\n");

  try {
    const issues = await fetchIssues();

    console.log(`[V23] Found ${issues.length} issues`);

    if (!issues.length) {
      console.log("[V23] No issues to process");
      return;
    }

    for (const issue of issues) {
      await handleIssue(issue);
    }

    console.log("\n[V23] Cycle complete\n");
  } catch (err) {
    console.error("[V23 ERROR]", err.message);
  }
}

run();
