#!/usr/bin/env node

require("dotenv").config();

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const https = require("https");
const { execSync } = require("child_process");

/**
 * =========================
 * STATE (RESTART SAFE)
 * =========================
 */

const STATE_FILE = "data/state.json";

let STATE = loadState();

function loadState() {
  try {
    return JSON.parse(fs.readFileSync(STATE_FILE));
  } catch {
    return {
      tasks: [],
      logs: [],
      lastRun: null,
      phase: "init",
      cycle: 0
    };
  }
}

function saveState() {
  fs.mkdirSync("data", { recursive: true });
  fs.writeFileSync(STATE_FILE, JSON.stringify(STATE, null, 2));
}

/**
 * =========================
 * LOGGING (PRODUCTION STYLE)
 * =========================
 */

function log(msg) {
  const line = `[CEO v10] ${msg}`;
  console.log(line);
  STATE.logs.push({ t: Date.now(), msg });
}

/**
 * =========================
 * GIT SAFE OPERATIONS
 * =========================
 */

function git(cmd) {
  try {
    execSync(cmd, { stdio: "inherit" });
  } catch (e) {
    log(`Git error: ${e.message}`);
  }
}

function commitStage(message) {
  git("git add .");
  git(`git commit -m "${message}"`);
}

/**
 * =========================
 * TASK ENGINE
 * =========================
 */

class Engine {
  add(task) {
    STATE.tasks.push({
      id: crypto.randomUUID(),
      status: "pending",
      created: Date.now(),
      ...task
    });
  }

  run() {
    const pending = STATE.tasks.filter(t => t.status === "pending");

    for (const t of pending) {
      log(`Executing task: ${t.type}`);

      try {
        if (t.type === "file") {
          fs.mkdirSync(path.dirname(t.path), { recursive: true });
          fs.writeFileSync(t.path, t.content);
          log(`Wrote file: ${t.path}`);
        }

        if (t.type === "code") {
          fs.mkdirSync(path.dirname(t.path), { recursive: true });
          fs.writeFileSync(
            t.path,
            `// AUTO GENERATED\nconsole.log("Module:", "${t.path}");`
          );
          log(`Generated code: ${t.path}`);
        }

        t.status = "done";
      } catch (e) {
        t.status = "failed";
        log(`FAILED task: ${e.message}`);
      }
    }
  }
}

const ENGINE = new Engine();

/**
 * =========================
 * PIPELINE PHASES
 * =========================
 */

function bootstrap() {
  log("Bootstrapping project");

  ["core", "backend", "frontend", "data"].forEach(d =>
    fs.mkdirSync(d, { recursive: true })
  );

  ENGINE.add({
    type: "file",
    path: "frontend/index.html",
    content: "<h1>BUDE AUTONOMOUS SYSTEM ONLINE</h1>"
  });

  STATE.phase = "plan";
}

function plan() {
  log("Planning architecture");

  ENGINE.add({
    type: "code",
    path: "backend/server.js"
  });

  ENGINE.add({
    type: "code",
    path: "backend/api.js"
  });

  ENGINE.add({
    type: "file",
    path: "README.md",
    content: "# Autonomous Dev System\nGenerated by CEO v10"
  });

  STATE.phase = "build";
  commitStage("Phase: plan completed");
}

function build() {
  log("Building frontend + backend");

  ENGINE.add({ type: "code", path: "frontend/app.js" });
  ENGINE.add({ type: "code", path: "frontend/sw.js" });

  STATE.phase = "finalize";
  commitStage("Phase: build completed");
}

function finalize() {
  log("Finalizing project");

  ENGINE.add({
    type: "file",
    path: "package.json",
    content: JSON.stringify({
      name: "autonomous-system",
      version: "1.0.0",
      scripts: { start: "node backend/server.js" }
    }, null, 2)
  });

  STATE.phase = "done";
  commitStage("Phase: finalize completed");
}

/**
 * =========================
 * MAIN LOOP (PRODUCTION SAFE)
 * =========================
 */

function loop() {
  log(`Cycle ${STATE.cycle++} start`);

  ENGINE.run();

  switch (STATE.phase) {
    case "init":
      bootstrap();
      break;

    case "plan":
      plan();
      break;

    case "build":
      build();
      break;

    case "finalize":
      finalize();
      break;

    case "done":
      log("SYSTEM COMPLETE");
      saveState();
      process.exit(0);
  }

  saveState();

  setTimeout(loop, 5000);
}

/**
 * =========================
 * STARTUP CHECKS
 * =========================
 */

function start() {
  log("Starting CEO v10 Production System");

  if (!fs.existsSync(".git")) {
    log("WARNING: Not a git repo (commits will fail)");
  }

  loop();
}

start();
