export const CONFIG = {
  TELEGRAM_TOKEN: 8805565958: AAFte5-PL77e7tBG9idnCMwsG37kUFJ9UTM,
  CHAT_ID: Bude Tech Control,

  GITHUB_OWNER: bude404-ops,
  GITHUB_REPO: Bude-Tech,
  GITHUB_TOKEN: ,

  SOLANA_WALLET: AnJDRjTaxtRbqYazSkRjLm1Y2jSfuCmHJhygKiNyrKmx,

  MODE: "V14_TELEGRAM_SAAS_FACTORY"
};
