export const CONFIG = {
  TELEGRAM_TOKEN: "YOUR_TELEGRAM_BOT_TOKEN",
  CHAT_ID: "YOUR_TELEGRAM_CHAT_ID",

  GITHUB_OWNER: "YOUR_GITHUB_USERNAME",
  GITHUB_REPO: "YOUR_REPO_NAME",
  GITHUB_TOKEN: "YOUR_GITHUB_TOKEN",

  SOLANA_WALLET: "YOUR_SOLANA_WALLET_ADDRESS",

  MODE: "V14_TELEGRAM_SAAS_FACTORY"
};
