const fs = require("fs");
const path = require("path");

function write(file, content) {
  const dir = path.dirname(file);
  if (dir && dir !== ".") fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(file, content);
}

function brain(input = "") {
  const text = input.toLowerCase();

  let files = [];

  // ── CREATE MODE ─────────────────────────────
  if (text.includes("create") || text.includes("build")) {
    files.push({
      file: "app/generated/page.jsx",
      content: `
export default function Page() {
  return (
    <div style={{ padding: 20 }}>
      <h1>Generated by BUDE AI</h1>
      <p>${input}</p>
    </div>
  );
}
`
    });
  }

  // ── FIX MODE ────────────────────────────────
  else if (text.includes("fix") || text.includes("error")) {
    files.push({
      file: "app/error.jsx",
      content: `
"use client";

export default function Error() {
  return (
    <div style={{ padding: 20 }}>
      <h2>Error Handler Active</h2>
    </div>
  );
}
`
    });
  }

  // ── DEFAULT STATUS ──────────────────────────
  else {
    files.push({
      file: "app/status/page.jsx",
      content: `
export default function Page() {
  return (
    <div style={{ padding: 20 }}>
      <h1>System Online</h1>
      <p>BUDE TECH OS Agent Active</p>
    </div>
  );
}
`
    });
  }

  // ── EXECUTE FILE WRITES ─────────────────────
  for (const f of files) {
    write(f.file, f.content);
    console.log("CREATED:", f.file);
  }

  return {
    input,
    created: files.map(f => f.file)
  };
}

// RUN FROM GITHUB ACTIONS
const input = process.argv.slice(2).join(" ");
brain(input);
