import random

# Generate blog/social content
def generate_content():
    # For demonstration purposes, generate a random article
    article = {
        'title': 'AI-generated article',
        'content': 'This is a sample article generated by AI'
    }
    return article

# Example usage
print(generate_content())